[build]
  command = "cd just_built_ide_production/frontend/just-built-frontend && npm install && npm run build"
  publish = "just_built_ide_production/frontend/just-built-frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"